### ISSUE TITLE
Readme needs to be updated to reference .Net 7.0

### ISSUE THREAD

**Issue by mediacloudusr** [logantgt/EcpEmuServer#6]
Hello,
The last release https://github.com/logantgt/EcpEmuServer/releases/tag/v0.3 relies on .Net 7.0 so the https://github.com/logantgt/EcpEmuServer/#readme should be updated to reference .Net 7.0 (for installation of runtime etc).

**Comment by logantgt** [comment]
Fixed in ddfddc1, good catch!

**Comment by mediacloudusr** [comment]
Thanks ! It works well for me on Windows Server.
Two comments
- I needed to declare the exe in Windows Firewall. There was no dialog bow asking for this.
- I run EcpEuServer as a Windows service, using https://nssm.cc/
